name: Music
version: ${project.version}
main: com.banyulescouts.music.Music
api-version: 1.17
depend: [ NoteBlockAPI ]
authors: [ Caldan112 ]
description: Play custom music

commands:
  music:
    description: Main command of plugin
